[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = { version = "1.3.1" }

[workspace]
members = ["day-1", "day-2"]

[workspace.dependencies]
csv = { version = "1.3.1" }
